name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  lint:
    name: Format
    runs-on: "${{ matrix.runs-on }}"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        runs-on: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"
      - uses: pre-commit/action@v3.0.1

  tests:
    runs-on: "${{ matrix.runs-on }}"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        runs-on: ["ubuntu-latest", "macos-latest", "windows-latest"]
    name: Check Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Only needed if using setuptools-scm

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install tests
        run: python -m pip install -e .[test]

      - name: Install dependencies
        run: |
          pip install setuptools
          pip install numpy
          pip install matplotlib
          pip install scipy

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

      - name: Test package
        run: python -m pytest -ra
